language: php
sudo: false

php:
    - 5.3

env:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 BEHAT_TEST=1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=2
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=3
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=master
  allow_failures:
    - env: DB=SQLITE CORE_RELEASE=master

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - if [ "$BEHAT_TEST" = "" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi
  - if [ "$BEHAT_TEST" = "1" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension; fi
  - cd ~/builds/ss
  - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
  - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script:
  - if [ -z "$COVERAGE" && -Z "$BEHAT_TEST" ]; then vendor/bin/phpunit -c ~/builds/ss/shop/phpunit.xml.dist; fi
  - if [ -n "$COVERAGE" && -z "$BEHAT_TEST" ]; then vendor/bin/phpunit -c ~/builds/ss/shop/phpunit.xml.dist --testsuite Split$COVERAGE --coverage-clover ~/builds/ss/shop/coverage.xml; fi
  - if [ -z "$COVERAGE" && -n "$BEHAT_TEST" ]; then vendor/bin/behat @shop; fi

after_script:
  - if [ -n "$COVERAGE" ]; then cd shop; fi
  - if [ -n "$COVERAGE" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -n "$COVERAGE" ]; then php ocular.phar code-coverage:upload -v --format=php-clover ~/builds/ss/shop/coverage.xml; fi

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a3720004986a0f249abc'
    on_success: change
    on_failure: always
    on_start: false
