language: php
sudo: false

php:
    - 5.3

env:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.1 BEHAT_TEST=1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=2
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=3
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=master
  allow_failures:
    - env: DB=SQLITE CORE_RELEASE=master

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - if [ "$BEHAT_TEST" = "" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi
  - if [ "$BEHAT_TEST" = "1" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension; fi
  - cd ~/builds/ss
  - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
  - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script: ./shop/tests/travis/run_build.sh

after_success: ./shop/tests/travis/upload_coverage.sh

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a3720004986a0f249abc'
    on_success: change
    on_failure: always
    on_start: false
